server:
  port: 8080
#  servlet:
#    session:
#      timeout:

logging:
  level:
    ROOT: info
    org:
      hibernate:
        SQL: DEBUG
        type: trace
      springframework.web: trace
spring:
  profiles:
    active: local
    devtools:
      livereload:
        enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true

  datasource:
    # 로컬
#    url: jdbc:mysql://localhost:3306/templet
    url: jdbc:mysql://keonhee.synology.me:3307/templet?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: chlznsl009!
    username: kuny87
    password: Chlrjsgml009!
    initialization-mode: always
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 100
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 개발
    properties:
      hibernate:
      format_sql: true
      hbm2ddl.auto: none
      show_sql: true
      generate-ddl: true
      database: mysql
      repositories.enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1084810483749-liiajjqpam8va79tp4fnbqute7pjes5o.apps.googleusercontent.com
            clientSecret: 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

          naver:
            client-id: Coi8qJIJ7zhAoj6ei8_7
            client-secret: j23CIdLQ05
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

