package com.wizvera.templet.logging;

/**
 * 로그 메시지에 대하여 MDC(Mapped Diagnostic Context) 키 값을 정의한 클래스이다.
 */
public interface LogMdcKey {
	String	MDC_KEY_CATEGORY	= "CATEGORY";
	String	MDC_KEY_LOG_MESSAGE	= "LOG_MESSAGE";
	String	MDC_KEY_ADMIN_ID	= "ADMIN_ID";
	String	MDC_KEY_RESULT		= "RESULT";
	String	MDC_KEY_ADMIN_IP	= "ADMIN_IP";
	String	MDC_KEY_ACTION		= "ACTION";
	String	MDC_KEY_ADMIN_TYPE	= "ADMIN_TYPE";
	String	MDC_KEY_AUDITEE_ID	= "AUDITEE_ID";

	String	DB_LOGGING_PREFIX	= "@P3AL#";
	String	DB_AUDIT_PREFIX		= "#TIDNDUA@";

	String MDC_KEY_ = "";
	// String MDC_KEY_ = "";
	// String MDC_KEY_ = "";
	// String MDC_KEY_ = "";

	// values for category //
	String	MDC_CATEGORY_LOGIN	= "LOGIN";
	String	MDC_CATEGORY_LOGOUT	= "LOGOUT";

	String	MDC_CATEGORY_PERMISSION_CREATE		= "PERM_C";
	String	MDC_CATEGORY_PERMISSION_READ_ALL	= "PERM_RA";
	String	MDC_CATEGORY_PERMISSION_READ		= "PERM_R";
	String	MDC_CATEGORY_PERMISSION_UPDATE		= "PERM_U";
	String	MDC_CATEGORY_PERMISSION_DELETE		= "PERM_D";

	String	MDC_CATEGORY_ADMIN_CREATE	= "ADM_C";
	String	MDC_CATEGORY_ADMIN_READ_ALL	= "ADM_RA";
	String	MDC_CATEGORY_ADMIN_READ		= "ADM_R";
	String	MDC_CATEGORY_ADMIN_UPDATE	= "ADM_U";
	String	MDC_CATEGORY_ADMIN_DELETE	= "ADM_D";

	String	MDC_CATEGORY_ADMINGROUP_CREATE		= "ADMGRP_C";
	String	MDC_CATEGORY_ADMINGROUP_READ_ALL	= "ADMGRP_RA";
	String	MDC_CATEGORY_ADMINGROUP_READ		= "ADMGRP_R";
	String	MDC_CATEGORY_ADMINGROUP_UPDATE		= "ADMGRP_U";
	String	MDC_CATEGORY_ADMINGROUP_DELETE		= "ADMGRP_D";

	String	MDC_CATEGORY_SUBSCRIBER_READ_ALL	= "SBSCRB_RA";
	String	MDC_CATEGORY_SUBSCRIBER_READ		= "SBSCRB";

	String	MDC_CATEGORY_CERT_ISSUE_HISTORY_READ		= "CERT_ISS_HISTR_RA";
	String	MDC_CATEGORY_CERT_REVOKE_HISTORY_READ		= "CERT_RVK_HISTR_RA";
	String	MDC_CATEGORY_REGISTER_HISTORY_READ			= "RGST_HISTR_RA";
	String	MDC_CATEGORY_SUBSCRIBER_SEARCH_HISTORY_READ	= "SBSCRB_SEARCH_HISTR_RA";

	String	MDC_CATEGORY_LOG_READ				= "LOG_RA";
	String	MDC_CATEGORY_CA_AUDIT_LOG_READ		= "CA_ADTLOG_RA";
	String	MDC_CATEGORY_RA_AUDIT_LOG_READ		= "RA_ADTLOG_RA";
	String	MDC_CATEGORY_OCSP_AUDIT_LOG_READ	= "OCSP_ADTLOG_RA";

	String MDC_CATEGORY_AUDITLOG_READ = "AUDIT_LOG_RA";

	String	MDC_CATEGORY_VERIFY_SIGNATURE	= "VERIFY_SIG";
	String	MDC_CATEGORY_REVOKE_CERT		= "REVOKE_CERT";

	String	MDC_CATEGORY_CA_CRL_INFO_READ	= "CRL_INFO_RA";
	String	MDC_CATEGORY_CA_CRL_INFO_UPDATE	= "CRL_INFO_U";
	String	MDC_CATEGORY_CA_CRL_RENEW		= "CRL_RENEW";
	String	MDC_CATEGORY_CA_CRL_CERT_VERIFY	= "CRL_CERT_VERIFY";

	String	MDC_CATEGORY_CERT_PROFILE_CREATE	= "CERT_PROFILE_C";
	String	MDC_CATEGORY_CERT_PROFILE_READ_ALL	= "CERT_PROFILE_RA";
	String	MDC_CATEGORY_CERT_PROFILE_READ		= "CERT_PROFILE_R";
	String	MDC_CATEGORY_CERT_PROFILE_UPDATE	= "CERT_PROFILE_U";
	String	MDC_CATEGORY_CERT_PROFILE_DELETE	= "CERT_PROFILE_D";

	String	MDC_CATEGORY_CA_CERT_PROFILE_READ_ALL	= "CA_CERT_PROFILE_RA";
	String	MDC_CATEGORY_CA_CERT_PROFILE_READ		= "CA_CERT_PROFILE_R";
	String	MDC_CATEGORY_CA_CERT_PROFILE_REGISTER	= "CA_CERT_PROFILE_C";
	String	MDC_CATEGORY_CA_CERT_PROFILE_UDPATE		= "CA_CERT_PROFILE_U";
	String	MDC_CATEGORY_CA_CERT_PROFILE_DELETE		= "CA_CERT_PROFILE_D";

	String	MDC_VALUE_INIT_SERVER			= "INIT-SERVER";
	String	MDC_VALUE_ISSUE_NEW_REG			= "ISSUE-NEW-REG";
	String	MDC_VALUE_ISSUE_ADD_REG			= "ISSUE-ADD-REG";
	String	MDC_VALUE_ISSUE_ADD_REG_AUTH	= "ISSUE-ADD-REG-AUTH";
	String	MDC_VALUE_LOG_SCHEDULER_FAIL	= "LOG-SCHEDULER-FAIL";
	String	MDC_VALUE_CHECK_BERRY_STATUS	= "CHECK-BERRY-STATUS";
	String	MDC_VALUE_ISSUE_NEW_BERRY		= "ISSUE-NEW-BERRY";
	String	MDC_VALUE_ISSUE_ADD_BERRY		= "ISSUE-ADD-BERRY";
	String	MDC_VALUE_RENEW_BERRY			= "RENEW-BERRY";
	String	MDC_VALUE_REVOKE_BERRY			= "REVOKE-BERRY";
	String	MDC_VALUE_SEARCH_BERRY			= "SEARCH-BERRY";
	String	MDC_VALUE_SEARCH_SECRET			= "SEARCH-SECRET";

	String	MDC_VALUE_SEARCH_HAS_VALID_SEED	= "SEARCH-HAS-VALID-SEED";
	String	MDC_VALUE_SEARCH_SEED			= "SEARCH-SEED";
	String	MDC_VALUE_CHECK_SEED_STATUS		= "CHECK-SEED-STATUS";
	String	MDC_VALUE_REVOKE_SEED			= "REVOKE-SEED";

	String	MDC_VALUE_CHANGE_PIN	= "CHANGE-PIN";
	String	MDC_VALUE_RESET_PIN		= "RESET-PIN";

	String	MDC_VALUE_REGISTER_PATTERN		= "REGISTER-PATTERN";
	String	MDC_VALUE_UNREGISTER_PATTERN	= "UNREGISTER-PATTERN";
	String	MDC_VALUE_SEARCH_PATTERN		= "SEARCH-PATTERN";
	String	MDC_VALUE_CHANGE_PATTERN		= "CHANGE-PATTERN";

	String	MDC_VALUE_REGISTER_FINGERPRINT		= "REGISTER-FINGERPRINT";
	String	MDC_VALUE_UNREGISTER_FINGERPRINT	= "UNREGISTER-FINGERPRINT";

	String	MDC_VALUE_REGISTER_FACE_ID		= "REGISTER-FACE-ID";
	String	MDC_VALUE_UNREGISTER_FACE_ID	= "UNREGISTER-FACE-ID";

	// values for requestor
	String MDC_VALUE_REQUESTOR_SERVER = "SERVER";

	// values for result //
	String	MDC_VALUE_RESULT_FAIL		= "FAIL";
	String	MDC_VALUE_RESULT_SUCCESS	= "SUCCESS";
	String	MDC_VALUE_RESULT_NONE		= "NONE";
}